### ISSUE TITLE
Not giving correct informtaion for many users

### ISSUE THREAD

**Issue by tmtanzeel** [CodeDotJS/quora-api#1]
I tested on my own i.e. Tanzeel-Mirza. But the information is wrong and values also not mapped to the correct keys. In fact many vital properties are null. Below is an extract.

> { profilePicture: null,
> biography: null,
> fullBio: null,
> publicAnswers: '55',
> questions: '6',
> posts: '28',
> followers: '18',
> following: null,
> edits: null,
> monthlyViews: null,
> totalViews: null }

While the data on the website is originally is

>Feeds
>   Profile
>   Answers76
>   Questions6
>   Shares0
>   Posts0
>   Followers 28
>   Following 18
>   Edits
    Activity

**Comment by CodeDotJS** [comment]
Last I updated this module in 2017. It's been two years and a lot of things have changed. Quora still makes changes on a daily basis. It was hard to keep this module up-to-date and that's why I stopped maintaing it. 

Although the module is poorly written, I'm down if you want to fix some features and send me a PR regarding it.

**Comment by tmtanzeel** [comment]
Oh. Ok. I really appreciate your effort. Good job @CodeDotJS
